import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        padding: 16,
        paddingTop: 10,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
    },
    listContainer: {
        padding: 16,
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    orderNumber: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    orderDetail: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 4,
    },
    statusContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
    },
    statusText: {
        fontSize: 14,
        fontWeight: '500',
    },
    modalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        width: '90%',
        maxHeight: '80%',
        padding: 16,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    confirmationContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        padding: 16,
        width: '80%',
    },
    modalDetail: {
        fontSize: 16,
        marginVertical: 16,
        textAlign: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 16,
    },
    confirmButton: {
        backgroundColor: '#28A745',
        padding: 12,
        borderRadius: 8,
        flex: 1,
        marginRight: 8,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#DC3545',
        padding: 12,
        borderRadius: 8,
        flex: 1,
        marginLeft: 8,
        alignItems: 'center',
    },
    updateButton: {
        backgroundColor: '#007BFF',
        padding: 12,
        borderRadius: 8,
        flex: 1,
        marginLeft: 8,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    buttonText2: {
        color: '#000000',
        fontSize: 16,
        fontWeight: '500',
    },
    disabledButton: {
        opacity: 0.7,
    },
    orderDetails: {
        maxHeight: '40%',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 1,
    },
    itemContainer: {
        backgroundColor: '#F8F9FA',
        padding: 12,
        borderRadius: 6,
        marginBottom: 8,
    },
    itemText: {
        fontSize: 14,
        marginBottom: 4,
    },
    itemDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    itemTotal: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    formField: {
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: 14,
        fontWeight: '500',
        marginBottom: 8,
    },
    pickerWrapper: {
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 8,
        overflow: 'hidden',
    },
    picker: {
        height: 50,
    },
    datePickerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 8,
    },
    dateText: {
        marginLeft: 8,
        fontSize: 14,
    },
    input: {
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
    },
    formHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    formActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 24,
    },
    partialPaymentButton: {
        backgroundColor: '#6C757D',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 16,
    },
    partialPaymentForm: {
        padding: 16,
    },
    orderActions: {
        borderTopWidth: 1,
        borderTopColor: '#DDD',
        paddingTop: 16,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 4,
    },
    backButton: {
        padding: 8,
    },
    refreshButton: {
        padding: 8,
    },
    title: {
        flex: 1,
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1A1A1A',
        marginLeft: 8,
    },
    filterSection: {
        backgroundColor: '#F8F9FA',
        padding: 8,
        marginBottom: 1,
    },
    dateContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 12,

    },
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f0f0f0',
        padding: 12,
        borderRadius: 8,
        flex: 0.48,
    },
    dateButtonText: {
        marginLeft: 8,
        color: '#333',
        fontSize: 14,
    },
    filterButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    button: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 12,
        borderRadius: 8,
        elevation: 1,
    },
    filterButton: {
        backgroundColor: '#007AFF',
        flex: 0.48,
    },
    resetButton: {
        backgroundColor: '#FF3B30',
        flex: 0.48,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        margin: 2,
        paddingHorizontal: 8,
        borderRadius: 8,
        elevation: 2,
      },
      searchIcon: {
        marginRight: 8,
      },
      searchInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 16,
      },
      imagePreview: {
        width: '100%',
        height: 200,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#ccc',
      },
      imagePickerContainer: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 10,
        padding: 20,
        marginBottom: 15,
        alignItems: 'center',
      },
      clearButton: {
        backgroundColor: '#FF0000',
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        marginVertical: 10,
        flexDirection: 'row',
      },
      clearButtonText: {
        color: '#FFF',
        fontSize: 16,
        marginLeft: 10,
      },
      formContainer: {
        marginBottom: 20,
      },
      inputCard: {
        marginBottom: 15,
      },
      label: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
        color: '#333',
      },
      textArea: {
        backgroundColor: 'white',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        padding: 12,
        marginBottom: 1,
        height: 60,
        textAlignVertical: 'top',
      },
      pickerContainer: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        marginBottom: 1,
      },
      imagePicker: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 10,
        padding: 20,
        marginBottom: 15,
        alignItems: 'center',
      },
      imagePlaceholder: {
        color: '#A9A9A9',
        textAlign: 'center',
      },

      submitButton: {
        backgroundColor: '#28A745',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
      },
      submitButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: 'bold',
      },
});